#WORKFLOW
#FICHIER DE DEPLOIEMENT CONTENANT LES CONFIGURATIONS NECESSAIRES,
#LES AJUSTEMENTS,
#LE FONCTIONNEMENT SUR LA GITHUB PAGES(CELLE QUI S'OCCUPE DE LA TOTALITE DU DEPLOIMENT)
name: Deploy to GitHub Pages
#DECLENCHEMENT DU DEPLOIEMENT A CHQ PUSH SUR MAIN
on:
  push:
    branches:
      - main
#TAF DU WORKFLOW
jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps: #ETAPES A SUIVRE
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      #EXECUTER DEPENDANCES
      - name: Install dependencies
        run: npm install --frozen-lockfile
      - name: Build website
        run: npm run build
      #ELEMENTS DE DEPLOIEMENT VIA NVL BRANCHE(gh-pages, qui ets dédiée à ça), QUI EST GENERÉ VIA TT CES ELEMENTS:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # faire la demande d'acces au token 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # designer la route du dist
          publish_dir: ./dist/rick-morty/browser
          # The following lines assign commit authorship to the official
          # GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com